// SPDX-License-Identifier: MPL-2.0
import { useEffect, useRef, useState } from 'react'
import { tr } from '../i18n'
import { community, ct } from './client'
type Row=Record<string,any>
export function CommunityFeedback({admin=false}:{admin?:boolean}){
  const [items,setItems]=useState<Row[]>([]),[detail,setDetail]=useState<Row|null>(null),[events,setEvents]=useState<Row[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState(''),[category,setCategory]=useState('bug'),[title,setTitle]=useState(''),[content,setContent]=useState(''),[note,setNote]=useState(''),[version,setVersion]=useState(0),[page,setPage]=useState(1),[total,setTotal]=useState(0)
  const pending=useRef<string|null>(null),prefix=admin?'/api/admin/feedback':'/api/feedback'
  useEffect(()=>{const controller=new AbortController();void community.get(`${prefix}?page=${page}&pageSize=20${filter?`&status=${filter}`:''}`,controller.signal).then(r=>{setItems(r.items);setTotal(r.total)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)});return()=>controller.abort()},[prefix,page,filter,version])
  const open=async(id:number)=>{setError('');try{const [r,events]=await Promise.all([community.get(`${prefix}/${id}`),community.get(`${prefix}/${id}/events`)]);setDetail(r.feedback||r);setEvents(events.items)}catch(e){setError((e as Error).message)}}
  const modify=async(kind:'status'|'notes'|'replies',value:string)=>{if(!detail||busy)return;setBusy(true);setError('');try{const b={version:detail.version,request_id:crypto.randomUUID(),...(kind==='status'?{status:value}:{content:value})};if(kind==='status')await community.patch(`${prefix}/${detail.id}/status`,b);else await community.post(`${prefix}/${detail.id}/${kind}`,b);setNote('');await open(detail.id);setVersion(v=>v+1)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <section><h2>{admin?ct('反馈收件箱','Feedback inbox'):ct('反馈与建议','Feedback and suggestions')}</h2>
    {admin?<label>{ct('按状态筛选','Filter by status')} <select value={filter} onChange={e=>{setFilter(e.target.value);setPage(1)}}><option value="">{ct('全部','All')}</option>{['new','in_progress','resolved','closed'].map(s=><option key={s}>{s}</option>)}</select></label>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');pending.current??=crypto.randomUUID();try{await community.post('/api/feedback',{category,title,content,request_id:pending.current});pending.current=null;setTitle('');setContent('');setVersion(v=>v+1)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>
      <div className="form-field"><label htmlFor="feedback-category">{ct('类型','Type')}</label><select id="feedback-category" value={category} onChange={e=>{setCategory(e.target.value);pending.current=null}}>{[['bug','Bug','Bug'],['suggestion','建议','Suggestion'],['question','问题','Question']].map(([value,zh,en])=><option value={value} key={value}>{ct(zh,en)}</option>)}</select></div>
      <div className="form-field"><label htmlFor="feedback-title">{ct('标题','Title')}</label><input id="feedback-title" maxLength={80} required value={title} onChange={e=>{setTitle(e.target.value);pending.current=null}}/></div><div className="form-field"><label htmlFor="feedback-content">{ct('内容（10–5000字）','Description (10–5000 characters)')}</label><textarea id="feedback-content" minLength={10} maxLength={5000} rows={4} required value={content} onChange={e=>{setContent(e.target.value);pending.current=null}}/></div><button className="btn btn-primary" disabled={busy}>{ct('提交反馈','Send feedback')}</button>
    </form>}
    {error&&<p className="error-text" role="alert">{tr(error)}</p>}
    <ul className="community-feedback-list">{items.map(r=><li key={r.id}><button className="link-btn" onClick={()=>void open(r.id)}>{r.title}</button><span className="muted">{r.status} · {r.author||`#${r.user_id}`}</span></li>)}</ul>
    <div className="feature-toolbar"><button className="btn btn-ghost" disabled={page===1} onClick={()=>setPage(p=>p-1)}>{ct('上一页','Previous')}</button><span>{page}</span><button className="btn btn-ghost" disabled={page*20>=total} onClick={()=>setPage(p=>p+1)}>{ct('下一页','Next')}</button></div>
    {detail&&<div className="community-detail"><div className="panel-head"><h3>{detail.title}</h3><button className="btn btn-ghost" onClick={()=>setDetail(null)}>{ct('收起','Close')}</button></div><p className="community-plain">{detail.content}</p><p className="muted">{detail.status} · {new Date(detail.created_at).toLocaleString()}</p>
      {events.map(r=><p className="community-plain" key={r.id}>{r.kind} · {r.content||`${r.from_status} → ${r.to_status}`}</p>)}
      {admin&&<><div className="feature-toolbar">{['in_progress','resolved','closed'].map(status=><button className="btn btn-ghost" key={status} disabled={busy||detail.status===status} onClick={()=>void modify('status',status)}>{status}</button>)}</div><label htmlFor="feedback-note">{ct('回复或内部备注','Reply or internal note')}</label><textarea id="feedback-note" maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} rows={3}/><div className="feature-toolbar"><button className="btn" disabled={busy||!note.trim()} onClick={()=>void modify('notes',note)}>{ct('保存内部备注','Save internal note')}</button><button className="btn btn-ghost" disabled={busy||!note.trim()} onClick={()=>void modify('replies',note)}>{ct('回复用户','Reply to user')}</button></div></>}
    </div>}
  </section>
}
